name             'openssl_cert'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures openssl_cert'
long_description 'Installs/Configures openssl_cert'
version          '0.1.0'
depends          'dbag'
